# CodeMagic 多平台构建配置
workflows:
  # 保留更完整的多平台配置
  flutter-multi:
    name: Flutter Multi-Platform Build
    environment:
      flutter: stable  # 使用稳定版Flutter
      xcode: latest    # iOS构建需要最新Xcode
    
    scripts:
      # Android构建（保留详细脚本）
      - name: Build Android APK
        script: |
          flutter build apk --release --target-platform android-arm,android-arm64
          echo "APK生成路径："
          ls build/app/outputs/flutter-apk/

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release
          echo "AAB生成路径："
          ls build/app/outputs/bundle/release/

      # 保留基础Android构建
      - flutter pub get
      - flutter build apk

    artifacts:
      # 合并产物路径
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
      - build/**/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your_email@example.com  # 替换为你的邮箱
